### ISSUE TITLE
External User Registration

### ISSUE THREAD

**Issue by ranierelacerda** [razasolutions/rafaela-velanes#1]
-Improvements in User entity;
-External registration page;
-Email confirmation;

**Comment by ranierelacerda** [comment]
Done.
Need user feedback.

**Comment by ranierelacerda** [comment]
Need user email confirmation???

**Comment by tazabreu** [comment]
Not necessary at the moment. Maybe this should be a core feature for incoming projects.

**Comment by ranierelacerda** [comment]
Need more user test and user feedback.
